### ISSUE TITLE
역시 $name님이에요... :blobaww: 가 발동될 확률을 문서에 공개해주세요.

### ISSUE THREAD

**Issue by leejseo** [junis3/cstodo#12]
요즘 많은 게임이 확률을 공개하지 않아 이슈가 되고 있습니다.
모범을 보여주세요. :blobaww:

**Comment by kimjg1119** [comment]
실시간으로 앱 제작자가 확률을 변동확률로 조작하는 것이 의심되는 사례가 다수 발생하였습니다. 해명하십시오.

**Comment by TAMREF** [comment]
봇의 확률에 관해서는 자율규제를 통해 모범적으로 운영하고 있음을 알려드립니다.
